- id: '1538793980800'
  alias: Run Vacuum Morning
  trigger:
  - at: 06:50
    platform: time
  condition:
  - condition: zone
    entity_id: person.alex
    zone: zone.home
  action:
  - entity_id: vacuum.xiaomi_vacuum
    service: vacuum.start
- id: '1538792980801'
  alias: Run Vacuum Afternoon
  trigger:
  - at: '12:30'
    platform: time
  - at: '16:30'
    platform: time
  condition:
  - condition: zone
    entity_id: person.alex
    zone: zone.home
  action:
  - data: {}
    entity_id: vacuum.xiaomi_vacuum
    service: vacuum.start
- id: '1559732747300'
  alias: Cold Morning AC
  trigger:
  - at: 05:15
    platform: time
  condition:
  - condition: zone
    entity_id: device_tracker.alex_phone
    zone: zone.home
  - below: '10'
    condition: numeric_state
    entity_id: sensor.bom_air_temp_c
  action:
  - data:
      host: 10.0.0.111
      packet:
      - JgAkAQABJ5MWEhUTFBMVNxQUFBMVExUSFDgUFBMUFDgUExUTFRIVExQTFRMVExQTFBQUNxUTFBQTFBUTFBMVExU2FRMUOBQTFBQUNxQUFQACkBQTFBQUExQUFBQTFBQUFBMVExUSFRMVEhUTFRMUExQUFBMVExUSFRMVEhUTFRMUExQUFBMVExQTFDgVNxQTFDgUAAUhAAEmlBQTFBQUExU3FRIVExUTFBMUOBQTFRMVNxQTFBQUExUTFRIUFBQTFRMUFBQ3FRMUExUTFBMUFBQUFDcVNxQ4FBMVExQ3FBQUAAKRFBMVExQTFRMVEhQUFBQUExQUFBMVExQTFBQUExUTFRMUExQUFBMUFBUSFRMVEhUTFRMUExQUFBMUOBQ4FBMVNxUADQUAAAAA
    service: broadlink.send
- id: '1589189995402'
  alias: Restart HA
  description: ''
  trigger:
  - at: 03:05
    platform: time
  - at: 09:30
    platform: time
  - at: '16:00'
    platform: time
  condition: []
  action:
  - data: {}
    service: homeassistant.restart
