- id: '1538793980800'
  alias: Run Vacuum Morning
  trigger:
  - at: 07:05
    platform: time
  condition:
  - condition: zone
    entity_id: device_tracker.alex_iphone
    zone: zone.home
  - condition: state
    entity_id: media_player.living_room_tv
    state: 'off'
  action:
  - service: vacuum.start
- id: '1538792980801'
  alias: Run Vacuum Afternoon
  trigger:
  - at: '12:30'
    platform: time
  - at: '17:15'
    platform: time
  condition:
  - condition: zone
    entity_id: device_tracker.alex_iphone
    zone: zone.home
  - condition: state
    entity_id: media_player.living_room_tv
    state: 'off'
  action:
  - service: vacuum.start
- id: '1559732747300'
  alias: Cold Morning AC
  trigger:
  - at: 05:50
    platform: time
  condition:
  - condition: zone
    entity_id: device_tracker.alex_iphone
    zone: zone.home
  - below: '5'
    condition: numeric_state
    entity_id: sensor.bom_feels_like_c
  action:
  - data:
      host: 10.0.0.111
      packet:
      - JgAkAQABJ5MWEhUTFBMVNxQUFBMVExUSFDgUFBMUFDgUExUTFRIVExQTFRMVExQTFBQUNxUTFBQTFBUTFBMVExU2FRMUOBQTFBQUNxQUFQACkBQTFBQUExQUFBQTFBQUFBMVExUSFRMVEhUTFRMUExQUFBMVExUSFRMVEhUTFRMUExQUFBMVExQTFDgVNxQTFDgUAAUhAAEmlBQTFBQUExU3FRIVExUTFBMUOBQTFRMVNxQTFBQUExUTFRIUFBQTFRMUFBQ3FRMUExUTFBMUFBQUFDcVNxQ4FBMVExQ3FBQUAAKRFBMVExQTFRMVEhQUFBQUExQUFBMVExQTFBQUExUTFRMUExQUFBMUFBUSFRMVEhUTFRMUExQUFBMUOBQ4FBMVNxUADQUAAAAA
    service: broadlink.send
