homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Australia/Brisbane
  customize: !include customize.yaml

http:
  base_url: !secret base_url

# Enables Default Home Assistant Components
default_config:

# More Config Items
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater

recorder:
  purge_interval: 1
  purge_keep_days: 7

# Phone App
ios:

weather:
  #  - platform: bom
  #    name: Toowoomba
  #    station: IDQ60901.95551

  - platform: openweathermap
    api_key: !secret openweatherapi

#################################################################
## Tracking
#################################################################

device_tracker router:
  - platform: ddwrt
    host: 10.0.0.1
    track_new_devices: no
    username: !secret router_user
    password: !secret router_pass

#################################################################
## Includes
#################################################################

automation: !include automations.yaml
person: !include persons.yaml
zone: !include zones.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
media_player: !include media_players.yaml
camera: !include cameras.yaml

#################################################################
## Other
#################################################################

vacuum:
  - platform: xiaomi_miio
    name: Xiaomi Vacuum
    host: 10.0.0.105
    token: !secret vacuum_token
