homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Australia/Brisbane


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml

#################################################################
## Sensors
#################################################################

# Weather Prediction
sensor:
  platform: yr


#################################################################
## Zones
#################################################################

zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 50
  icon: mdi:home

zone 2:
  name: Ergon
  latitude: -27.573183
  longitude: 151.920584
  radius: 100
  icon: mdi:briefcase

zone 3:
  name: Hospital
  latitude: -27.570010
  longitude: 151.945301
  radius: 150
  icon: mdi:hospital
