homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Australia/Brisbane


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
recorder:
  purge_interval: 2
  purge_keep_days: 10

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google


#################################################################
## Tracking
#################################################################

device_tracker router:
  - platform: ddwrt
    host: 10.0.0.1
    track_new_devices: no
    username: !secret router_user
    password: !secret router_pass

  
#################################################################
## Cameras
#################################################################

camera:
  - platform: rpi_camera

#################################################################
## Sensors
#################################################################

sensor bomweather:
  - platform: bom
    station: IDQ60901.95551
    name: Toowoomba
    monitored_conditions:
      - apparent_t
      - cloud
      - air_temp
      - dewpt
      - rain_trace
      - rel_hum
      - vis_km
      - wind_spd_kmh


sensor netspeed:
  platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - download
    - upload

#################################################################
## Switches
#################################################################

switch:
  - platform: broadlink
    host: 10.0.0.111
    mac: '34:EA:34:8E:FA:55'
    switches:    
        tv_lg:
          friendly_name: "LG Tv Power"
          command_on: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='    
        
#################################################################
## Media Players
#################################################################

media_player tv:
  platform: lg_netcast
  host: 10.0.0.121
  access_token: 712781
  name: Living Room TV

media_player denon:
  platform: denonavr

media_player cast:
  platform: cast

media_player plex:
  platform: plex

#################################################################
## Zones
#################################################################

zone home:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 50
  icon: mdi:home

zone ergon:
  name: Ergon
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 100
  icon: mdi:briefcase

zone hospital:
  name: Hospital
  latitude: !secret hospital_latitude
  longitude: !secret hospital_longitude
  radius: 150
  icon: mdi:hospital

group: !include groups.yaml
automation: !include automations.yaml
