homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Australia/Brisbane


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  # base_url: example.duckdns.org:8123
  trusted_networks:
    - 127.0.0.1
    - 10.0.0.0/24
    - fd00::/8
  ip_ban_enabled: True
  login_attempts_threshold: 5
  

# Checks for available updates
updater:
  reporting: no

# Discover some devices automatically
discovery:
ios:

# Show the map
map:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
recorder:
  purge_interval: 1
  purge_keep_days: 7

# View all events in a logbook
logbook:

# Track the sun
sun:

weather:
  - platform: bom
    name: Toowoomba
    station: IDQ60901.95551
    
# Text to speech
tts:
  platform: google


#################################################################
## Tracking
#################################################################

device_tracker router:
  - platform: ddwrt
    host: 10.0.0.1
    track_new_devices: no
    username: !secret router_user
    password: !secret router_pass



#################################################################
## Switches
#################################################################

switch:
  - platform: broadlink
    host: 10.0.0.111
    mac: '34:EA:34:8E:FA:55'
    switches:    
        tv_lg:
            friendly_name: "LG TV"
            command_on: 'JgBoAAABJpQQFBEUETgRFBEUEBUQFBEUETgRORAVEDkROBE5EDkRORAUERQRFBA5ERQQFRAUERQROBE5EDkRFBE4ETkQORE5EAAFJQABKEkRAAxPAAEmSxEADFAAASdJEQAMUAABKEkQAA0F'
            command_off: 'JgBoAAABJpQQFBEUETgRFBEUEBUQFBEUETgRORAVEDkROBE5EDkRORAUERQRFBA5ERQQFRAUERQROBE5EDkRFBE4ETkQORE5EAAFJQABKEkRAAxPAAEmSxEADFAAASdJEQAMUAABKEkQAA0F'

        air_con:
            friendly_name: "Kelvinator AirCon"
            command_on: 'JgAkAQABJ5MWEhUTFBMVNxQUFBMVExUSFDgUFBMUFDgUExUTFRIVExQTFRMVExQTFBQUNxUTFBQTFBUTFBMVExU2FRMUOBQTFBQUNxQUFQACkBQTFBQUExQUFBQTFBQUFBMVExUSFRMVEhUTFRMUExQUFBMVExUSFRMVEhUTFRMUExQUFBMVExQTFDgVNxQTFDgUAAUhAAEmlBQTFBQUExU3FRIVExUTFBMUOBQTFRMVNxQTFBQUExUTFRIUFBQTFRMUFBQ3FRMUExUTFBMUFBQUFDcVNxQ4FBMVExQ3FBQUAAKRFBMVExQTFRMVEhQUFBQUExQUFBMVExQTFBQUExUTFRMUExQUFBMUFBUSFRMVEhUTFRMUExQUFBMUOBQ4FBMVNxUADQUAAAAA'
            command_off: 'JgAkAQABJ5QUExUTFRIUFBQTFRMVExQTFTcUExQUFTcUExUTFBMVExUSFBQVEhUTFRMUNhUUFBMVExUSFRMUFBQ3FBQVNhQUFRMUNxUTFAACkBUTFBQUExQUFRIVExQTFRMVEhUTFRMUExQUFBMVExUSFRMUExQUFRMUExQUFBMVExUSFRMUExUTFDgUNxUTFRIVAAUgAAEmlBQUFRIVExUSFRMVExQTFRMUNxQUFBMVNxUTFBMVExQTFBQUExUTFBQUExQ4FBMUFBUSFBQUFBQTFDgUNxQ4FBQUExU3FBMVAAKQFBQUExUTFBMVExUSFRMVEhUTFRMUExUTFRIVExUSFRMUFBQTFRMUExUTFBMVExUSFRMUFBQTFRMUNhY3FRIVExQADQUAAAAA'

vacuum:
  - platform: xiaomi_miio
    name: Xiaomi Vacuum
    host: 10.0.0.127
    token: !secret vacuum_token


#################################################################
## Includes
#################################################################    
        
sensor: !include sensor.yaml
media_player: !include media_player.yaml
zone: !include zones.yaml
camera: !include camera.yaml
group: !include groups.yaml
automation: !include automations.yaml
