homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Australia/Brisbane


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:
  reporting: no

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
recorder:
  purge_interval: 2
  purge_keep_days: 10

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google


#################################################################
## Tracking
#################################################################

device_tracker router:
  - platform: ddwrt
    host: 10.0.0.1
    track_new_devices: no
    username: !secret router_user
    password: !secret router_pass


#################################################################
## Switches
#################################################################

switch:
  - platform: broadlink
    host: 10.0.0.111
    mac: '34:EA:34:8E:FA:55'
    switches:    
        tv_lg:
          friendly_name: "LG Tv Power"
          command_on: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='    
        
sensor: !include sensor.yaml
media_player: !include media_player.yaml
zone: !include zones.yaml
camera: !include camera.yaml
group: !include groups.yaml
automation: !include automations.yaml
