- platform: bom
  station: IDQ60901.95551
  monitored_conditions:
    - apparent_t
    - air_temp
    - rain_trace

- platform: broadlink
  host: 10.0.0.101
  mac: "34:EA:34:8E:FA:55"
  scan_interval: 60
  monitored_conditions:
    - 'temperature'
