#################################################################
## Switches
#################################################################

- platform: broadlink
  host: 10.0.0.101
  mac: "34:EA:34:8E:FA:55"
  switches:
    tv_lg:
      friendly_name: "LG TV"
      command_on: "JgBoAAABJpQQFBEUETgRFBEUEBUQFBEUETgRORAVEDkROBE5EDkRORAUERQRFBA5ERQQFRAUERQROBE5EDkRFBE4ETkQORE5EAAFJQABKEkRAAxPAAEmSxEADFAAASdJEQAMUAABKEkQAA0F"
      command_off: "JgBoAAABJpQQFBEUETgRFBEUEBUQFBEUETgRORAVEDkROBE5EDkRORAUERQRFBA5ERQQFRAUERQROBE5EDkRFBE4ETkQORE5EAAFJQABKEkRAAxPAAEmSxEADFAAASdJEQAMUAABKEkQAA0F"

    air_con:
      friendly_name: "Kelvinator AirCon"
      command_on: "JgAkAQABJ5MWEhUTFBMVNxQUFBMVExUSFDgUFBMUFDgUExUTFRIVExQTFRMVExQTFBQUNxUTFBQTFBUTFBMVExU2FRMUOBQTFBQUNxQUFQACkBQTFBQUExQUFBQTFBQUFBMVExUSFRMVEhUTFRMUExQUFBMVExUSFRMVEhUTFRMUExQUFBMVExQTFDgVNxQTFDgUAAUhAAEmlBQTFBQUExU3FRIVExUTFBMUOBQTFRMVNxQTFBQUExUTFRIUFBQTFRMUFBQ3FRMUExUTFBMUFBQUFDcVNxQ4FBMVExQ3FBQUAAKRFBMVExQTFRMVEhQUFBQUExQUFBMVExQTFBQUExUTFRMUExQUFBMUFBUSFRMVEhUTFRMUExQUFBMUOBQ4FBMVNxUADQUAAAAA"
      command_off: "JgAkAQABJ5QUExUTFRIUFBQTFRMVExQTFTcUExQUFTcUExUTFBMVExUSFBQVEhUTFRMUNhUUFBMVExUSFRMUFBQ3FBQVNhQUFRMUNxUTFAACkBUTFBQUExQUFRIVExQTFRMVEhUTFRMUExQUFBMVExUSFRMUExQUFRMUExQUFBMVExUSFRMUExUTFDgUNxUTFRIVAAUgAAEmlBQUFRIVExUSFRMVExQTFRMUNxQUFBMVNxUTFBMVExQTFBQUExUTFBQUExQ4FBMUFBUSFBQUFBQTFDgUNxQ4FBQUExU3FBMVAAKQFBQUExUTFBMVExUSFRMVEhUTFRMUExUTFRIVExUSFRMUFBQTFRMUExUTFBMVExUSFRMUFBQTFRMUNhY3FRIVExQADQUAAAAA"