title: Guinman Household
views:
  - title: Home
    id: home
    cards:
      - type: entities
        title: People
        show_header_toggle: true
        entities:
          - device_tracker.alex_iphone
          - device_tracker.rachael_nexus    
      - type: weather-forecast
        entity: weather.bom_toowoomba
      - type: entities
        title: IR Blaster
        show_header_toggle: false
        entities:
          - switch.air_con
          - switch.tv_lg
      - type: entities
        title: Vacuum cleaner
        show_header_toggle: false
        entities:
          - vacuum.xiaomi_vacuum
      - type: media-control
        entity: media_player.living_room_tv
      - type: media-control
        entity: media_player.denon_avrx1000
  - title: Cameras
    id: cameras
    icon: mdi:cctv
    cards:        
      - type: picture-entity
        title: Backyard
        entity: camera.backyard
        camera_image: camera.backyard
        show_info: true
        tap_action: dialog    
      - type: picture-entity
        title: PI3
        entity: camera.pi3
        camera_image: camera.pi3
        show_info: true
        tap_action: dialog        